# Generated by Django 4.1.3 on 2025-07-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('METER_READER', 'Meter Reader'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50),
        ),
    ]
