# Generated by Django 5.2.4 on 2025-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_phone_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['role'], name='account_acc_role_9e7c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='account_acc_is_acti_b336d2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='account_acc_email_ddd6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['last_name', 'first_name'], name='account_acc_last_na_7964a9_idx'),
        ),
    ]
