# Generated by Django 5.2.4 on 2025-07-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_acc_role_9e7c6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_acc_is_acti_b336d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_acc_email_ddd6d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='account_acc_last_na_7964a9_idx',
        ),
    ]
