# Generated by Django 5.2.4 on 2025-07-25 05:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate per unit of consumption', max_digits=10)),
                ('min_consumption', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum consumption for this rate tier', max_digits=10)),
                ('max_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum consumption for this rate tier (leave blank for no maximum)', max_digits=10, null=True)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Rate',
                'verbose_name_plural': 'Billing Rates',
                'ordering': ['min_consumption'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consump_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount charged per unit of water consumed', max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional amount charged for late payments', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.BigIntegerField(null=True, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(max_length=15, null=True, unique=True)),
                ('address', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_billed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='main.client')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date'],
                'unique_together': {('client', 'reading_date')},
            },
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('billing_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='main.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('meter_reading', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_bill', to='main.meterreading')),
            ],
            options={
                'verbose_name': 'Water Bill',
                'verbose_name_plural': 'Water Bills',
                'ordering': ['-billing_date', 'client'],
            },
        ),
    ]
