# Generated by Django 5.2.4 on 2025-07-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_metric_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='updated_at',
        ),
    ]
