# Generated by Django 4.1.3 on 2025-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_waterbill_checkout_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbill',
            name='reading',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.TextField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
    ]
