# Generated by Django 5.2.4 on 2025-07-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_waterbill_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('checkout_request_id', models.CharField(max_length=100)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='main.waterbill')),
            ],
        ),
    ]
