# Generated by Django 5.2.4 on 2025-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='consump_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='meter_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='waterbill',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
