# Generated by Django 5.2.4 on 2025-07-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_client_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbill',
            name='status',
            field=models.TextField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partially Paid', 'Partially Paid')], default='Pending', null=True),
        ),
    ]
